"""
Complete File Transfer Implementation for LSNP
"""

import os
import base64
import time
import threading
from typing import Dict, Optional


class FileTransfer:
    """Represents an ongoing file transfer."""
    
    def __init__(self, file_id: str, filename: str, filesize: int, filetype: str, 
                 sender: str, receiver: str, description: str = ""):
        """Initialize a file transfer."""
        self.file_id = file_id
        self.filename = filename
        self.filesize = filesize
        self.filetype = filetype
        self.sender = sender
        self.receiver = receiver
        self.description = description
        
        # Transfer state
        self.chunks = {}  # chunk_index -> chunk_data
        self.total_chunks = 0
        self.received_chunks = 0
        self.chunk_size = 1024  # Default chunk size (1KB)
        self.created_at = time.time()
        self.last_chunk_time = time.time()
        self.completed = False
        self.accepted = False
        
        # For sending
        self.file_path = None
        self.chunks_sent = 0
        self.offer_acked = False
    
    def add_chunk(self, chunk_index: int, chunk_data: str, total_chunks: int, chunk_size: int):
        """Add a chunk to the transfer."""
        if chunk_index in self.chunks:
            return  # Duplicate chunk
        
        self.chunks[chunk_index] = chunk_data
        self.total_chunks = total_chunks
        self.chunk_size = chunk_size
        self.received_chunks = len(self.chunks)
        self.last_chunk_time = time.time()
        
        # Check if transfer is complete
        if self.received_chunks == self.total_chunks:
            self.completed = True
    
    def is_complete(self) -> bool:
        """Check if all chunks have been received."""
        return self.completed and self.received_chunks == self.total_chunks
    
    def get_progress(self) -> float:
        """Get transfer progress as a percentage."""
        if self.total_chunks == 0:
            return 0.0
        return (self.received_chunks / self.total_chunks) * 100
    
    def reassemble_file(self) -> bytes:
        """Reassemble the file from chunks."""
        if not self.is_complete():
            raise ValueError("Transfer not complete")
        
        # Sort chunks by index and concatenate
        file_data = b""
        for i in range(self.total_chunks):
            if i not in self.chunks:
                raise ValueError(f"Missing chunk {i}")
            
            chunk_data = base64.b64decode(self.chunks[i])
            file_data += chunk_data
        
        return file_data


class FileManager:
    """Manages file transfers for an LSNP client."""
    
    def __init__(self, client, default_chunk_size: int = 1024):
        """Initialize the file manager.
        
        Args:
            client: The LSNP client instance
            default_chunk_size: Default chunk size in bytes (default: 1KB)
        """
        self.client = client
        self.incoming_transfers = {}  # file_id -> FileTransfer
        self.outgoing_transfers = {}  # file_id -> FileTransfer
        self.downloads_dir = "downloads"
        self.default_chunk_size = default_chunk_size
        
        # Create downloads directory
        os.makedirs(self.downloads_dir, exist_ok=True)
        
        # Store pending offers for user decision
        self.pending_offers = {}  # file_id -> (transfer, message_id, sender_ip)
        
        # Track recent ACKs to avoid duplicate processing
        self.recent_acks = {}  # message_id -> timestamp
        
        # Track message IDs generated by this manager for ACK routing
        self._sent_message_ids = set()
        self._message_ids_lock = threading.Lock()
    
    def is_tracking_message(self, message_id: str) -> bool:
        """Check if this manager sent a message with the given ID."""
        with self._message_ids_lock:
            return message_id in self._sent_message_ids
    
    def _track_message_id(self, message_id: str):
        """Track a message ID that this manager sent."""
        with self._message_ids_lock:
            self._sent_message_ids.add(message_id)
            # Keep only recent message IDs (last 100) to prevent memory leak
            if len(self._sent_message_ids) > 100:
                # Remove oldest (this is a simple approach, could be improved with timestamps)
                self._sent_message_ids.pop()
    
    def offer_file(self, target_user: str, file_path: str, description: str = "", ttl: int = 3600, chunk_size: int = None):
        """Offer to send a file to another user.
        
        Args:
            target_user: The user ID to send the file to
            file_path: Path to the file to send
            description: Optional description of the file
            ttl: Token time-to-live in seconds
            chunk_size: Chunk size in bytes (uses default if None)
        """
        if not os.path.exists(file_path):
            print(f"File not found: {file_path}")
            return None
        
        # Use default chunk size if not specified
        if chunk_size is None:
            chunk_size = self.default_chunk_size
        
        # Validate chunk size (minimum 128 bytes, maximum 64KB)
        chunk_size = max(128, min(chunk_size, 65536))
        
        # Extract target IP
        if "@" not in target_user:
            print(f"Invalid target user format: {target_user}")
            return None
        
        target_ip = self.client._get_peer_ip(target_user)
        if not target_ip:
            print(f"Cannot determine IP for user: {target_user}")
            return None
        
        # Get file information
        filename = os.path.basename(file_path)
        filesize = os.path.getsize(file_path)
        filetype = self._get_mime_type(file_path)
        file_id = self._generate_file_id()
        
        # Create transfer record with specified chunk size
        transfer = FileTransfer(file_id, filename, filesize, filetype, 
                              self.client.user_id, target_user, description)
        transfer.file_path = file_path
        transfer.chunk_size = chunk_size  # Store the chunk size for this transfer
        self.outgoing_transfers[file_id] = transfer
        
        # Send file offer
        token = self.client.token_manager.generate_token("file", ttl)
        message_id = self.client._generate_message_id()
        self._track_message_id(message_id)  # Track for ACK routing
        
        message_data = {
            "TYPE": "FILE_OFFER",
            "FROM": self.client.user_id,
            "TO": target_user,
            "FILENAME": filename,
            "FILESIZE": str(filesize),
            "FILETYPE": filetype,
            "FILEID": file_id,
            "CHUNK_SIZE": str(chunk_size),  # Include chunk size in offer
            "DESCRIPTION": description,
            "MESSAGE_ID": message_id,
            "TIMESTAMP": str(int(time.time())),
            "TOKEN": token
        }
        
        # Send to multiple ports to ensure delivery
        self._send_to_multiple_ports(target_ip, message_data)
        
        target_name = self.client.known_peers.get(target_user, {}).get('display_name', target_user.split('@')[0])
        print(f"Offering to send {filename} ({filesize} bytes, {chunk_size} byte chunks) to {target_name}")
        
        return file_id
    
    def _send_to_multiple_ports(self, target_ip: str, message_data: dict):
        """Send message to multiple ports to ensure delivery."""
        from protocol import ProtocolHandler
        
        message = ProtocolHandler.format_message(**message_data)
        ports = [50999, 51000, 51001, 51002]  # Common LSNP ports
        
        sent_count = 0
        for port in ports:
            try:
                self.client.peer.sock.sendto(message.encode('utf-8'), (target_ip, port))
                sent_count += 1
            except Exception as e:
                if self.client.verbose:
                    self.client.logger.log_error(f"Failed to send to {target_ip}:{port}", {"error": str(e)})
        
        if self.client.verbose:
            self.client.logger.log_send(message_data, f"{target_ip} (multiple ports)")
    
    def handle_file_offer(self, message: Dict[str, str], sender_ip: str):
        """Handle an incoming file offer."""
        from_user = message.get('FROM')
        filename = message.get('FILENAME')
        filesize = int(message.get('FILESIZE', 0))
        filetype = message.get('FILETYPE')
        file_id = message.get('FILEID')
        chunk_size = int(message.get('CHUNK_SIZE', self.default_chunk_size))  # Get chunk size from offer
        description = message.get('DESCRIPTION', '')
        message_id = message.get('MESSAGE_ID')
        
        # Create transfer record with chunk size from offer
        transfer = FileTransfer(file_id, filename, filesize, filetype, 
                              from_user, self.client.user_id, description)
        transfer.chunk_size = chunk_size  # Store the sender's chunk size
        
        # Store as pending offer instead of auto-accepting
        self.pending_offers[file_id] = (transfer, message_id, sender_ip)
        
        # Non-verbose: single-line prompt per spec
        sender_name = self.client.known_peers.get(from_user, {}).get('display_name', from_user.split('@')[0])
        if not self.client.verbose:
            print(f"User {sender_name} is sending you a file do you accept?")
            print(f"Type: accept {file_id} | reject {file_id}")
            return
        
        # Verbose: detailed offer info
        print(f"\n=== FILE OFFER RECEIVED ===")
        print(f"From: {sender_name} ({from_user})")
        print(f"File: {filename} ({filesize} bytes)")
        print(f"Type: {filetype}")
        print(f"ID: {file_id}")
        if description:
            print(f"Description: {description}")
        print(f"MESSAGE_ID: {message_id}")
        print(f"Type: accept {file_id} | reject {file_id}")
        print("=" * 30)
    
    def accept_file_offer(self, file_id: str) -> bool:
        """Accept a pending file offer."""
        if file_id not in self.pending_offers:
            print(f"No pending file offer with ID: {file_id}")
            return False
        
        transfer, message_id, sender_ip = self.pending_offers[file_id]
        
        # Move to incoming transfers and accept
        self.incoming_transfers[file_id] = transfer
        self._accept_file_offer(transfer, message_id, sender_ip)
        
        # Remove from pending
        del self.pending_offers[file_id]
        
        return True
    
    def reject_file_offer(self, file_id: str) -> bool:
        """Reject a pending file offer."""
        if file_id not in self.pending_offers:
            print(f"No pending file offer with ID: {file_id}")
            return False
        
        transfer, message_id, sender_ip = self.pending_offers[file_id]
        
        # Send rejection ACK
        if message_id:
            self._send_ack(message_id, transfer.sender, "REJECTED")
        
        sender_name = self.client.known_peers.get(transfer.sender, {}).get('display_name', transfer.sender.split('@')[0])
        print(f"Rejected file offer: {transfer.filename} from {sender_name}")
        
        # Remove from pending
        del self.pending_offers[file_id]
        
        return True
    
    def list_pending_offers(self):
        """List all pending file offers."""
        if not self.pending_offers:
            print("No pending file offers.")
            return
        
        print("\n=== PENDING FILE OFFERS ===")
        for file_id, (transfer, _, _) in self.pending_offers.items():
            sender_name = self.client.known_peers.get(transfer.sender, {}).get('display_name', transfer.sender.split('@')[0])
            print(f"ID: {file_id}")
            print(f"  From: {sender_name} ({transfer.sender})")
            print(f"  File: {transfer.filename} ({transfer.filesize} bytes)")
            print(f"  Type: {transfer.filetype}")
            if transfer.description:
                print(f"  Description: {transfer.description}")
            print(f"  Commands: accept {file_id} | reject {file_id}")
            print()
        print("=" * 30)

    def _accept_file_offer(self, transfer: FileTransfer, message_id: str, sender_ip: str):
        """Accept a file offer and send ACK."""
        transfer.accepted = True
        
        # Send ACK to confirm acceptance
        if message_id:
            self._send_ack(message_id, transfer.sender, "ACCEPTED")
        
        print(f"\nAccepted file transfer: {transfer.filename}")
    
    def _send_ack(self, message_id: str, to_user: str, status: str):
        """Send an ACK message."""
        target_ip = self.client._get_peer_ip(to_user)
        if not target_ip:
            return
        
        message_data = {
            "TYPE": "ACK",
            "MESSAGE_ID": message_id,
            "STATUS": status
        }
        
        self._send_to_multiple_ports(target_ip, message_data)
        
        if self.client.verbose:
            self.client.logger.log_send(message_data, f"{target_ip} (ACK {status})")
    
    def handle_ack(self, message_id: str, status: str):
        """Handle ACK messages for file transfers."""
        # Only handle ACKs for messages we actually sent
        if not self.is_tracking_message(message_id):
            return
            
        # Avoid duplicate processing
        current_time = time.time()
        if message_id in self.recent_acks:
            if current_time - self.recent_acks[message_id] < 2:  # 2 second dedup window
                return
        self.recent_acks[message_id] = current_time
        
        # Clean old ACKs
        old_acks = [mid for mid, timestamp in self.recent_acks.items() 
                   if current_time - timestamp > 10]
        for mid in old_acks:
            del self.recent_acks[mid]
        
        # Remove the message ID from tracking since we've received the ACK
        with self._message_ids_lock:
            self._sent_message_ids.discard(message_id)
        
        # Find which transfer this ACK belongs to
        for file_id, transfer in self.outgoing_transfers.items():
            if not transfer.offer_acked:
                if status in ["ACCEPTED", "RECEIVED"]:
                    transfer.offer_acked = True
                    print(f"File offer accepted! Starting transfer of {transfer.filename}")
                    # Start sending file chunks
                    threading.Thread(target=self._send_file_chunks, 
                                   args=(transfer,), daemon=True).start()
                    return
                elif status == "REJECTED":
                    receiver_name = self.client.known_peers.get(transfer.receiver, {}).get('display_name', transfer.receiver.split('@')[0])
                    print(f"File offer rejected by {receiver_name}: {transfer.filename}")
                    # Remove the transfer since it was rejected
                    del self.outgoing_transfers[file_id]
                    return
    
    def _send_file_chunks(self, transfer: FileTransfer):
        """Send file chunks for an accepted transfer."""
        try:
            with open(transfer.file_path, 'rb') as f:
                file_data = f.read()
            
            # Use the chunk size specified for this transfer
            chunk_size = transfer.chunk_size if hasattr(transfer, 'chunk_size') else self.default_chunk_size
            total_chunks = (len(file_data) + chunk_size - 1) // chunk_size
            
            token = self.client.token_manager.generate_token("file")
            target_ip = self.client._get_peer_ip(transfer.receiver)
            
            print(f"Sending {transfer.filename} in {total_chunks} chunks of {chunk_size} bytes each...")
            
            # Send chunks
            for i in range(total_chunks):
                start_idx = i * chunk_size
                end_idx = min(start_idx + chunk_size, len(file_data))
                chunk_data = file_data[start_idx:end_idx]
                
                # Encode chunk as base64
                encoded_chunk = base64.b64encode(chunk_data).decode('utf-8')
                
                message_data = {
                    "TYPE": "FILE_CHUNK",
                    "FROM": self.client.user_id,
                    "TO": transfer.receiver,
                    "FILEID": transfer.file_id,
                    "CHUNK_INDEX": str(i),
                    "TOTAL_CHUNKS": str(total_chunks),
                    "CHUNK_SIZE": str(len(chunk_data)),
                    "TOKEN": token,
                    "DATA": encoded_chunk
                }
                
                self._send_to_multiple_ports(target_ip, message_data)
                
                # Progress indicator
                progress = ((i + 1) / total_chunks) * 100
                print(f"Progress: {progress:.1f}% ({i + 1}/{total_chunks} chunks)")
                
                # Small delay to avoid overwhelming the network
                time.sleep(0.05)  # 50ms delay between chunks
            
            print(f"Finished sending {transfer.filename}")
            
        except Exception as e:
            print(f"Error sending file chunks: {e}")
    
    def handle_file_chunk(self, message: Dict[str, str], sender_ip: str):
        """Handle an incoming file chunk."""
        file_id = message.get('FILEID')
        chunk_index = int(message.get('CHUNK_INDEX', 0))
        total_chunks = int(message.get('TOTAL_CHUNKS', 0))
        chunk_size = int(message.get('CHUNK_SIZE', 0))
        chunk_data = message.get('DATA', '')
        
        if file_id not in self.incoming_transfers:
            if self.client.verbose:
                self.client.logger.log_error(f"Received chunk for unknown transfer: {file_id}")
            return
        
        transfer = self.incoming_transfers[file_id]
        if not transfer.accepted:
            if self.client.verbose:
                self.client.logger.log_error(f"Received chunk for unaccepted transfer: {file_id}")
            return
        
        # Add chunk
        transfer.add_chunk(chunk_index, chunk_data, total_chunks, chunk_size)
        
        # Show progress only in verbose mode (spec: no output until complete)
        if self.client.verbose:
            progress = transfer.get_progress()
            print(f"Receiving {transfer.filename}: {progress:.1f}% ({chunk_index + 1}/{total_chunks} chunks)")
        
        # Check if transfer is complete
        if transfer.is_complete():
            self._save_received_file(transfer)
    
    def _save_received_file(self, transfer: FileTransfer):
        """Save a completed file transfer."""
        try:
            file_data = transfer.reassemble_file()
            
            # Create safe filename
            safe_filename = self._sanitize_filename(transfer.filename)
            file_path = os.path.join(self.downloads_dir, safe_filename)
            
            # Handle filename conflicts
            counter = 1
            original_path = file_path
            while os.path.exists(file_path):
                name, ext = os.path.splitext(original_path)
                file_path = f"{name}_{counter}{ext}"
                counter += 1
            
            # Save file
            with open(file_path, 'wb') as f:
                f.write(file_data)
            
            # Spec: Non-verbose prints only one line when complete
            if not self.client.verbose:
                print(f"File transfer of {transfer.filename} is complete")
            else:
                sender_name = self.client.known_peers.get(transfer.sender, {}).get('display_name', transfer.sender.split('@')[0])
                print(f"File transfer complete!")
                print(f"   {transfer.filename} saved to {file_path}")
                print(f"   {len(file_data)} bytes received from {sender_name}")
            
            # Send completion notification
            self._send_file_received(transfer)
        except Exception as e:
            print(f"Error saving file: {e}")
    
    def _send_file_received(self, transfer: FileTransfer):
        """Send a FILE_RECEIVED message."""
        target_ip = self.client._get_peer_ip(transfer.sender)
        if not target_ip:
            return
        
        message_data = {
            "TYPE": "FILE_RECEIVED",
            "FROM": self.client.user_id,
            "TO": transfer.sender,
            "FILEID": transfer.file_id,
            "STATUS": "COMPLETE",
            "TIMESTAMP": str(int(time.time()))
        }
        
        self._send_to_multiple_ports(target_ip, message_data)
        
        if self.client.verbose:
            self.client.logger.log_send(message_data, f"{target_ip} (FILE_RECEIVED)")
    
    def handle_file_received(self, message: Dict[str, str], sender_ip: str):
        """Handle a FILE_RECEIVED message."""
        file_id = message.get('FILEID')
        status = message.get('STATUS')
        from_user = message.get('FROM')
        
        if file_id in self.outgoing_transfers:
            transfer = self.outgoing_transfers[file_id]
            if status == "COMPLETE":
                if self.client.verbose:
                    receiver_name = self.client.known_peers.get(from_user, {}).get('display_name', from_user.split('@')[0])
                    print(f"[DEBUG] FILE_RECEIVED from {receiver_name} for {transfer.filename}")
                # No output in non-verbose per spec
                # Optionally cleanup transfer state here
    
    def _generate_file_id(self) -> str:
        """Generate a unique file ID."""
        import random
        import string
        return ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))
    
    def _get_mime_type(self, file_path: str) -> str:
        """Get MIME type based on file extension."""
        ext = os.path.splitext(file_path)[1].lower()
        mime_types = {
            '.txt': 'text/plain',
            '.jpg': 'image/jpeg',
            '.jpeg': 'image/jpeg',
            '.png': 'image/png',
            '.gif': 'image/gif',
            '.pdf': 'application/pdf',
            '.zip': 'application/zip',
            '.mp3': 'audio/mpeg',
            '.mp4': 'video/mp4',
            '.py': 'text/x-python'
        }
        return mime_types.get(ext, 'application/octet-stream')
    
    def _sanitize_filename(self, filename: str) -> str:
        """Sanitize filename for safe saving."""
        # Remove/replace dangerous characters
        unsafe_chars = '<>:"/\\|?*'
        for char in unsafe_chars:
            filename = filename.replace(char, '_')
        
        # Limit length
        if len(filename) > 255:
            name, ext = os.path.splitext(filename)
            filename = name[:255-len(ext)] + ext
        
        return filename
    
    def list_transfers(self):
        """List current file transfers."""
        print("\n=== File Transfers ===")
        
        active_transfers = False
        
        if self.incoming_transfers:
            print("Incoming:")
            for file_id, transfer in self.incoming_transfers.items():
                if transfer.is_complete():
                    status = "Complete"
                else:
                    status = f"{transfer.get_progress():.1f}%"
                
                sender_name = self.client.known_peers.get(transfer.sender, {}).get('display_name', transfer.sender.split('@')[0])
                print(f"   {transfer.filename} from {sender_name} - {status}")
                active_transfers = True
        
        if self.outgoing_transfers:
            print("Outgoing:")
            for file_id, transfer in self.outgoing_transfers.items():
                if not transfer.offer_acked:
                    status = "Waiting for acceptance"
                else:
                    status = "Sending"
                
                receiver_name = self.client.known_peers.get(transfer.receiver, {}).get('display_name', transfer.receiver.split('@')[0])
                print(f"   {transfer.filename} to {receiver_name} - {status}")
                active_transfers = True
        
        if not active_transfers:
            print("No active transfers")
        
        print("=====================\n")
    
    def set_default_chunk_size(self, chunk_size: int):
        """Set the default chunk size for file transfers.
        
        Args:
            chunk_size: Chunk size in bytes (minimum 128, maximum 64KB)
        """
        # Validate chunk size (minimum 128 bytes, maximum 64KB)
        chunk_size = max(128, min(chunk_size, 65536))
        self.default_chunk_size = chunk_size
        print(f"Default chunk size set to {chunk_size} bytes")
    
    def get_default_chunk_size(self) -> int:
        """Get the current default chunk size."""
        return self.default_chunk_size